apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dnazureaks-5d53"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dnazureaks-5d53"
  template:
    metadata:
      labels:
        app: "dnazureaks-5d53"
    spec:
      containers:
        - name: "dnazureaks-5d53"
          image: "containerregistry2exam.azurecr.io/dnazureaks"
          ports:
          - containerPort: 80